package com.example.petclinicapp.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.MenuBook
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.petclinicapp.ui.theme.ClinicTeal
import com.example.petclinicapp.ui.theme.TextDark
import com.example.petclinicapp.ui.theme.TextGray
import com.example.petclinicapp.ui.theme.BackgroundWhite

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PolicyScreen(title: String, content: String, onBack: () -> Unit) {
    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(title, fontWeight = FontWeight.Bold, color = TextDark) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back", tint = ClinicTeal)
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = Color.White)
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .padding(padding)
                .fillMaxSize()
                .background(BackgroundWhite)
                .verticalScroll(rememberScrollState())
        ) {
            Column(modifier = Modifier.padding(start = 24.dp, end = 24.dp, bottom = 24.dp)) {
                // Header
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Surface(
                        shape = RoundedCornerShape(12.dp),
                        color = ClinicTeal.copy(alpha = 0.1f),
                        modifier = Modifier.size(48.dp)
                    ) {
                        Box(contentAlignment = Alignment.Center) {
                            Icon(Icons.Default.MenuBook, contentDescription = null, tint = ClinicTeal)
                        }
                    }
                    Spacer(modifier = Modifier.width(16.dp))
                    Column {
                        Text("Clinic Protocols", fontSize = 22.sp, fontWeight = FontWeight.Bold, color = TextDark)
                        Text("Legal guidelines and standards", color = TextGray, fontSize = 14.sp)
                    }
                }

                Spacer(modifier = Modifier.height(32.dp))

                Card(
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(32.dp),
                    colors = CardDefaults.cardColors(containerColor = Color.White),
                    elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
                ) {
                    Column(modifier = Modifier.padding(24.dp)) {
                        Text(
                            text = content,
                            style = MaterialTheme.typography.bodyLarge.copy(
                                lineHeight = 26.sp,
                                color = TextDark,
                                fontSize = 15.sp
                            )
                        )
                    }
                }
                
                Spacer(modifier = Modifier.height(16.dp))
            }
        }
    }
}

object PolicyContent {
    val PrivacyPolicy = """
        Last Updated: March 2026
        
        1. Our Commitment to Privacy
        At PetClinic, your privacy is paramount. We understand that medical information about you and your pets is personal. We are committed to protecting it and being transparent about our practices.

        2. Data Collection & Usage
        We collect information necessary to provide expert veterinary care:
        • Contact Details: Name, email, and phone for account management.
        • Patient Records: Pet species, breed, medical history, and treatment plans.
        • Documentation: Clinical notes and prescriptions generated by our medical staff.
        
        This data is used exclusively to facilitate healthcare services, appointment scheduling, and emergency triage.

        3. Information Security
        We implement industry-standard AES-256 encryption and stringent access controls to protect your data. Our backend infrastructure is monitored 24/7 for security threats.

        4. Third-Party Sharing
        We do not sell your personal data. Information is only shared with authorized medical providers within our network or when required by law to protect public health or animal welfare.

        5. Your Rights
        You have the right to access your medical records, update your profile, and request data deletion at any time through our support channels.
    """.trimIndent()

    val TermsOfService = """
        Last Updated: March 2026

        1. Acceptance of Terms
        By accessing or using the PetClinic mobile application, you agree to be bound by these professional terms of service. Our platform facilitates medical coordination between pet owners and licensed veterinary practitioners.

        2. Medical Disclaimer
        The app is a management tool. In life-threatening emergencies, please proceed immediately to the nearest 24/7 veterinary hospital regardless of app queue status.

        3. User Responsibilities
        Users must provide accurate, current, and complete information during registration. You are responsible for maintaining the confidentiality of your account credentials.

        4. Operational Guidelines
        • Appointments: Must be booked through the official triage system.
        • Prescriptions: Valid only when issued by licensed specialists within the platform.
        • Conduct: Any misuse of the platform or harassment of medical staff will result in immediate termination of access.

        5. Liability
        PetClinic provides the digital infrastructure for medical coordination. While we strive for 100% uptime, we are not liable for service interruptions caused by external factors.
    """.trimIndent()
}
